task:
    freebsd_instance:
      matrix:
        - image: freebsd-13-1-release-amd64

    timeout_in: 90m
    prerequisites_script:
      # portsnap  --interactive fetch && portsnap extract
      # Only download /usr/ports/graphics but not other ports; https://stackoverflow.com/a/52269934/2988
      - git clone --depth 1 --filter=blob:none --sparse https://git.FreeBSD.org/ports.git /usr/ports
      - ( cd /usr/ports ; git sparse-checkout set graphics ; cd - )
      - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
      - pkg install -y graphics/gpu-firmware-kmod
    build_package_script:
      - cd /usr/ports ; env BATCH=1 make -C graphics/drm-510-kmod package
    binary_artifacts:
      path: "/usr/ports/graphics/drm-510-kmod/work/pkg/*"
