task:
    freebsd_instance:
      matrix:
        - image: freebsd-13-1-release-amd64
    env:
      CIRRUS_CLONE_DEPTH: 1
      GITHUB_TOKEN: ENCRYPTED[02e03fdb075b334413c7bf1d38bce7f31ff19319bd163e0a3509a8ebe90dea8f3339571a87c69b8355d3bb8d796a632a]

    timeout_in: 90m
    prerequisites_script:
      - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
      - pkg install -y git-lite graphics/gpu-firmware-kmod
      # portsnap  --interactive fetch && portsnap extract
      # Only download /usr/ports/graphics but not other ports; https://stackoverflow.com/a/52269934/2988
      - rm -rf /usr/ports
      - git clone --depth 1 --filter=blob:none --sparse https://git.FreeBSD.org/ports.git /usr/ports
      - ( cd /usr/ports ; git sparse-checkout set graphics ; cd - )
    build_package_script:
      - cd /usr/ports ; env BATCH=1 make -C graphics/drm-510-kmod package
    binary_artifacts:
      path: "../../usr/ports/graphics/drm-510-kmod/work/pkg/*"
